nav:
  - Home: 'index.md'
  - About:
    - General Information : 'about.md'
    - Teaching Team: 'team.md'
    - Schedule: 'schedule.md'
  - Notes: 
    - 1. What is a Program?: "notes/01-program.md"
    - 2. Computational Problems: "notes/02-algo.md"
    - 3. Functions: "notes/03-func.md"
    - 4. Types: "notes/04-type.md"
    - 5. First C Program: "notes/05-first-c.md"
    - 6. CS1010 I/O: "notes/06-cs1010-io.md"
    - 7. Arithmetic Operations: "notes/07-arithmetic-ops.md"
    - 8. Conditional Statement: "notes/08-if-else.md"
    - 9. Logical Expression: "notes/09-logical-exp.md"
    - 10. Assertion: "notes/10-assert.md"
    - 11. Loop: "notes/11-loop.md"
    - 12. Invariant: "notes/12-invariant.md"
    - 13. Call Stack: "notes/13-call-stack.md"
    - 14. Fixed-Length Array: "notes/14-array.md"
    - 15. Pointers: "notes/15-pointers.md"
    - 16. Call by Reference: "notes/16-call-by-reference.md"
    - 17. Heap: "notes/17-heap.md"
    - 18. String: "notes/18-string.md"
    - 19. Multidimensional Array: "notes/19-md-array.md"
    - 20. Efficiency: "notes/20-efficiency.md"
    - 21. Searching: "notes/21-search.md"
    - 22. Sorting: "notes/22-sort.md"
    - 23. Tower of Hanoi: "notes/23-tower.md"
    - 24. Permutation: "notes/24-permutation.md"
    - 25. N-Queens: "notes/25-queens.md"
    - 26. Structure: "notes/26-struct.md"
    - 27. Standard I/O: "notes/27-stdio.md"
  - Lab Guides: 
    - Unix:
      - Background: "guides/unix-background.md"
      - Essentials: "guides/unix-essentials.md"
      - Advanced: "guides/unix-advanced.md"
    - Vim:
      - Philosophy: "guides/vim-philosophy.md"
      - Quick Lesson: "guides/vim-quick-lessons.md"
      - Setup: "guides/vim-setup.md"
      - Extensions: "guides/vim-plugins.md"
      - Tips: "guides/vim-tips.md"
    - PE Nodes:
      - Programming Environments: "guides/environments.md"
      - Linking GitHub to PE: "guides/github.md"
      - Using tmate: "guides/tmate.md"
    - C Programming:
      - C in CS1010: 'guides/c-in-cs1010.md'
      - Common Clang Messages: 'guides/messages.md'
      - CS1010 I/O Library: "guides/library.md"
      - C Style Guide: 'guides/style.md'
      - C Documentation Guide: 'guides/documentation.md'
      - Compiling with Clang: 'guides/clang.md'
  - Exercises: 
      - Guide to Exercises: "guides/exercises.md"
      - 0. I/O, Types, and Arithmetic: 'exercises/ex00.md'
      - 1. Conditionals: 'exercises/ex01.md'
      - 2. Loops: 'exercises/ex02.md'
      - 3. Fixed-Length Arrays: 'exercises/ex03.md'
      - 4. Dynamic Arrays and Strings: 'exercises/ex04.md'
      - 5. Multi-dimensional Arrays: 'exercises/ex05.md'
      - 6. Searching and Sorting: 'exercises/ex06.md'
      - 7. Recursions : 'exercises/ex07.md'
      - 8. Struct : 'exercises/ex08.md'
  - Readings: "readings.md" 


theme: 
  name: material
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

  palette:
    primary: cs1010ay2324s1
    accent: cs1010ay2324s1
  shortcuts:
    previous: 72 #h
    next: 76 #l
    search: 191 #/

site_name: CS1010 Programming Methodology
# repo_url: https://github.com/nus-cs1010/1819-s1
site_url: https://nus-cs1010.github.io/2324-s1
copyright: Copyright by Department of Computer Science, National University of Singapore 2023
# remote_branch: gh-pages
use_directory_urls: false
markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.highlight:
     linenums: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map: {
        bang: "!",
        dollar: "$",
        parenthesis-left: "(",
        parenthesis-right: ")",
      }
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 

#plugins:
#  - search:
#      lang: en
#      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

extra_javascript:
  - javascripts/config.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - 'stylesheets/extra.css'
  - 'https://fonts.googleapis.com/css?family=Roboto:400,700'
  - 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap'
